# MkDocs configuration file
site_name: BuildAX v2
site_description: BuildAX v2 project documentation  

repo_url: https://code.google.com/p/openmovement/
repo_name: Google Code

site_author: Sam Mitchell Finnigan, Newcastle University
copyright: Creative Commons 3.0 BY Atribution licence

#theme: readthedocs
#extra_css: extra.css
theme_dir: theme

pages:
- [index.md, Home]
- [connecting.md, Connection Guide]
- [commands.md, Router Commands]
- [user-guide.md, Web Interface User Guide]
- [developer-api.md, Developer Guide]

#use_directory_urls: False
url_format: file

